language: python
python:
  - 3.3
  - 3.4

install:
- pip install --upgrade setuptools
- pip install pyflakes
- pip install pep8
- pip install coveralls --use-mirrors
- pip install aiohttp
- python setup.py develop

script:
- pyflakes aiohttp_security tests
- pep8 aiohttp_security tests
- coverage run --source=aiohttp_security setup.py test

after_success:
- coveralls

env:
  matrix:
  - PYTHONASYNCIODEBUG=1
  - PYTHONASYNCIODEBUG=0
